### ISSUE TITLE
How can I manage to filter by Date 

### ISSUE THREAD

**Issue by jainprashul** [bi-tm/express-nedb-rest#17]
I tried via regex but cannot find a workaround.

**Comment by bi-tm** [comment]
Sorry, i didn't work on it for some time. I will have to try it by my own. But i have some friends here and test it tomorrow earliest.

**Comment by jainprashul** [comment]
can u tell me how to filter via date i have some docs in collection .
Btw thanks for reply.

**Comment by jainprashul** [comment]
http://localhost:5200/api/ledger?$filter=date%20$regex%20{%22date%22%20:%202020-08-28T09:14:46.964Z}

for above its showing this 

unvalid $filter Lexical error on line 1. Unrecognized text. date $regex {"date" : 2020-08-28 ------------^

**Comment by bi-tm** [comment]
Hello Jain,

the REST service recognizes text fields with ISO-8601 timestamp and converts the string into a date-object. 

For example, the following call would save the timestamp in NEDB as a date-object:
```
POST http://localhost:8000/test 
content-type: application/json
{
    "name": "alpha",
    "timestamp": "2020-09-11T22:19:00Z"  
}
```

This conversion also occurs with filters.

For example, the following call should find the object stored above:
`GET http://localhost:8000/test?$filter=timestamp $gte 2020-09-11T00:00:00Z` 

A REGEX search only works for strings. But because the timestamp is stored as a date object, you cannot perform a REGEX search on it.

You can disable the date conversion by creating the API middleware with following configuration:
`var restApi = expressNedbRest({convertToDate:false});`

Kind regards
Torsten
